{
 "title": "Parnell Aerospace",
 "description": "Parnell Aerospace",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "PlantName",
    "label": "Plant",
    "query": "boltmaker\n| where messageTimestamp > ago(7d)\n| project  PlantName = plantName\n| distinct PlantName\n| where PlantName != 'null'\n| order by PlantName asc"
   },
   {
    "name": "ProductionLine",
    "label": "Production Line",
    "query": "boltmaker\n| where plantName == '$PlantName'\n| where messageTimestamp > ago(7d)\n| project  ProductionLine = productionLine\n| distinct ProductionLine\n| where ProductionLine != 'null'\n| order by ProductionLine asc"
   },
   {
    "name": "ShiftNumber",
    "label": "Shift Number",
    "query": "boltmaker\n| where plantName == '$PlantName'\n| where productionLine == '$ProductionLine'\n| where messageTimestamp > ago(7d)\n| project  ShiftNumber = tostring(shiftNumber)\n| distinct ShiftNumber\n| order by ShiftNumber asc"
   }
  ]
 },
 "panels": [
  {
   "title": "OEE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where productionLine == '$ProductionLine'\n| where shiftNumber == tolong('$ShiftNumber')\n| where $__timeFilter(messageTimestamp)\n| extend healthy = iff(machineHealth == 'Healthy',1, 0)  \n| extend error= iff(machineHealth == 'Error',1, 0)  \n| extend warning = iff(machineHealth == 'Warning',1, 0)  \n| summarize totalPartsMade = sum(round(totalPartsMade,2)), defectivePartsMade = sum(round(defectivePartsMade,2)), healthyCount = sum(healthy), errorCount = sum(error), warningCount = sum(warning)\n| extend Quality = iff(totalPartsMade>0,(totalPartsMade -  defectivePartsMade)*100/totalPartsMade,0.00)\n| extend Availability = (healthyCount -  errorCount)*100/healthyCount  \n| extend Performance = iff((healthyCount + warningCount + errorCount)>0,round(healthyCount*100/(healthyCount + warningCount + errorCount),2),0.00)\n| extend OEE = (Performance+Quality+Availability)/3\n| project OEE, ago(1m)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Quality",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where productionLine == '$ProductionLine'\n| where shiftNumber == tolong('$ShiftNumber')\n| where $__timeFilter(messageTimestamp)\n| summarize totalPartsMade = sum(round(totalPartsMade,2)), defectivePartsMade = sum(round(defectivePartsMade,2))\n| extend Quality = iff(totalPartsMade>0,(totalPartsMade -  defectivePartsMade)*100/totalPartsMade,0.00)\n| project Quality, ago(1m)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where productionLine == '$ProductionLine'\n| where shiftNumber == tolong('$ShiftNumber')\n| where $__timeFilter(messageTimestamp)\n| extend healthy = iff(machineHealth == 'Healthy',1, 0)  \n| extend error= iff(machineHealth == 'Error',1, 0)  \n| extend warning = iff(machineHealth == 'Warning',1, 0)\n| summarize healthyCount = sum(healthy), errorCount = sum(error), warningCount = sum(warning)\n| extend Performance = iff((healthyCount + warningCount + errorCount)>0,round(healthyCount*100/(healthyCount + warningCount + errorCount),2),0.00)\n| project Performance, ago(1m)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where productionLine == '$ProductionLine'\n| where shiftNumber == tolong('$ShiftNumber')\n| where $__timeFilter(messageTimestamp)\n| extend healthy = iff(machineHealth == 'Healthy',1, 0)  \n| extend error= iff(machineHealth == 'Error',1, 0)  \n| extend warning = iff(machineHealth == 'Warning',1, 0)  \n| summarize healthyCount = sum(healthy), errorCount = sum(error), warningCount = sum(warning)\n| extend Availability = (healthyCount -  errorCount)*100/healthyCount  \n| project Availability, ago(1m) ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Parts Made",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where productionLine == '$ProductionLine'\n| where shiftNumber == tolong('$ShiftNumber')\n| where $__timeFilter(messageTimestamp) \n| summarize totalPartsMade = sum(round(totalPartsMade,2)) by bin(messageTimestamp, 5m)\n| project totalPartsMade = totalPartsMade, messageTimestamp\n| order by messageTimestamp asc ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Defective Parts Made",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where productionLine == '$ProductionLine'\n| where shiftNumber == tolong('$ShiftNumber')\n| where $__timeFilter(messageTimestamp) \n| summarize defectivePartsMade = sum(defectivePartsMade) by bin(messageTimestamp, 5m)\n| project defectivePartsMade, messageTimestamp\n| order by messageTimestamp asc ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Temp.",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where productionLine == '$ProductionLine'\n| where shiftNumber == tolong('$ShiftNumber')\n| where $__timeFilter(messageTimestamp) \n| project temperature, messageTimestamp \n| order by messageTimestamp asc ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where productionLine == '$ProductionLine'\n| where shiftNumber == tolong('$ShiftNumber')\n| where $__timeFilter(messageTimestamp) \n| where machineHealth == 'Healthy' or machineHealth ==  'Warning'\n| summarize upTime = count() by bin(messageTimestamp, 1m)\n| order by messageTimestamp asc ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where productionLine == '$ProductionLine'\n| where shiftNumber == tolong('$ShiftNumber')\n| where $__timeFilter(messageTimestamp) \n| where machineHealth == 'Error'\n| summarize downTime = count() by bin(messageTimestamp, 1m)\n| order by messageTimestamp asc ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Max Temp.",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where productionLine == '$ProductionLine'\n| where shiftNumber == tolong('$ShiftNumber')\n| where $__timeFilter(messageTimestamp) \n| project temperature, messageTimestamp \n| order by messageTimestamp asc ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Min Temp.",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where productionLine == '$ProductionLine'\n| where shiftNumber == tolong('$ShiftNumber')\n| where $__timeFilter(messageTimestamp) \n| project temperature, messageTimestamp \n| order by messageTimestamp asc ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Avg. Oil Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where productionLine == '$ProductionLine'\n| where shiftNumber == tolong('$ShiftNumber')\n| where $__timeFilter(messageTimestamp) \n| project oilLevel, messageTimestamp \n| order by messageTimestamp asc ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "OEE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where productionLine == '$ProductionLine'\n| where shiftNumber == tolong('$ShiftNumber')\n| where $__timeFilter(messageTimestamp)\n| extend healthy = iff(machineHealth == 'Healthy',1, 0)  \n| extend error= iff(machineHealth == 'Error',1, 0)  \n| extend warning = iff(machineHealth == 'Warning',1, 0)  \n| summarize totalPartsMade = sum(round(totalPartsMade,2)), defectivePartsMade = sum(round(defectivePartsMade,2)), healthyCount = sum(healthy), errorCount = sum(error), warningCount = sum(warning) by bin(messageTimestamp, 1h)\n| extend Quality = iff(totalPartsMade>0,(totalPartsMade -  defectivePartsMade)*100/totalPartsMade,0.00)\n| extend Availability = (healthyCount -  errorCount)*100/healthyCount  \n| extend Performance = iff((healthyCount + warningCount + errorCount)>0,round(healthyCount*100/(healthyCount + warningCount + errorCount),2),0.00)\n| extend OEE = (Performance+Quality+Availability)/3\n| project OEE, messageTimestamp\n| order by messageTimestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Parts Made",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where productionLine == '$ProductionLine'\n| where shiftNumber == tolong('$ShiftNumber')\n| where $__timeFilter(messageTimestamp)\n| project messageTimestamp, totalPartsMade\n| summarize totalPartsMade = sum(totalPartsMade) by bin(messageTimestamp, 1h)\n| order by messageTimestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Oil Level",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where productionLine == '$ProductionLine'\n| where shiftNumber == tolong('$ShiftNumber')\n| where $__timeFilter(messageTimestamp)\n| project messageTimestamp, oilLevel\n| summarize oilLevel = avg(oilLevel) by bin(messageTimestamp, 1h) \n| order by messageTimestamp asc ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where productionLine == '$ProductionLine'\n| where shiftNumber == tolong('$ShiftNumber')\n| where $__timeFilter(messageTimestamp)\n| project messageTimestamp, temperature\n| summarize temperature = avg(temperature) by bin(messageTimestamp, 1h)\n| order by messageTimestamp asc ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "OEE by Production Line",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where shiftNumber == tolong('$ShiftNumber')\n| where $__timeFilter(messageTimestamp)\n| extend healthy = iff(machineHealth == 'Healthy',1, 0)  \n| extend error= iff(machineHealth == 'Error',1, 0)  \n| extend warning = iff(machineHealth == 'Warning',1, 0)  \n| summarize totalPartsMade = sum(round(totalPartsMade,2)), defectivePartsMade = sum(round(defectivePartsMade,2)), healthyCount = sum(healthy), errorCount = sum(error), warningCount = sum(warning) by bin(messageTimestamp, 1h), productionLine\n| extend Quality = iff(totalPartsMade>0,(totalPartsMade -  defectivePartsMade)*100/totalPartsMade,0.00)\n| extend Availability = (healthyCount -  errorCount)*100/healthyCount  \n| extend Performance = iff((healthyCount + warningCount + errorCount)>0,round(healthyCount*100/(healthyCount + warningCount + errorCount),2),0.00)\n| extend OEE = (Performance+Quality+Availability)/3\n| project OEE, productionLine, messageTimestamp\n| order by messageTimestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Parts Made by Production Line",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "database": "parnell",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "boltmaker\n| where plantName == '$PlantName'\n| where $__timeFilter(messageTimestamp)\n| summarize partsMade = sum(totalPartsMade) by productionLine, bin(messageTimestamp, 5m)\n| project messageTimestamp, productionLine, partsMade\n| order by messageTimestamp asc",
     "querySource": "raw"
    }
   ]
  }
 ]
}